### ISSUE TITLE
Swiching speaker to non-featured results in error

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-legacy#12]
Switching a speaker to non-featured is not possible and results in an error.

![screenshot from 2017-12-20 11-22-33](https://user-images.githubusercontent.com/1583873/34202558-56a68d38-e578-11e7-809a-5232d53135d6.png)

**Comment by shubham-padia** [comment]
@mariobehling Unable to recreate this issue. Can you tell me what the error message says?

**Comment by mariobehling** [comment]
Please go to TAKASU Masakazu and try to switch off "Featured Speaker".

![screenshot from 2017-12-29 08-11-55](https://user-images.githubusercontent.com/1583873/34431494-0493500e-ec70-11e7-9d80-05aa3128b1fe.png)
