### ISSUE TITLE
The sponsor section overscrolls beyond the footer ( UI bug )

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/open-event-legacy#75]
**Describe the bug**
After I selected the "Sava and proceed" the sponsor section ended up over scrolling beyond the footer section.

**To Reproduce**
1. Go to event creation section
2. Click on **save and proceed**

**Expected behavior**
The app should not scroll beyond the Footer

**Screenshots**
![screenshot-eventyay com-2019 01 29-16-10-08](https://user-images.githubusercontent.com/19551058/51902788-c8cc7600-23e0-11e9-9072-368bd10b021b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser FF Quantum - Version 64.0

**Would like to work on this**
Nope, free for all.

**Comment by mariobehling** [comment]
This is not a bug, that prevents us from running the application. The main goal is to make a switch to V2. @AakashMallik please help to get the next version ready instead: https://next.eventyay.com/
