### ISSUE TITLE
Unable to save event when information other than ticket's information is changed

### ISSUE THREAD

**Issue by invinciblycool** [fossasia/open-event-legacy#8]
#**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**/**Steps to reproduce**

 - Create an event
 - Enable the ticketing system
 - Add a ticket and give it a name
 - Now save and proceed
 - Now go back to the previous wizard
 - Now change any information(say event description or create another ticket) except the ticket's information
 - And click on save and proceed

The event is not saved.

**Expected behavior:**
The event should be saved

**Comment by shubham-padia** [comment]
Please proceed

**Comment by mariobehling** [comment]
This bug does not seem to appear at the moment. So, I am closing this PR. Thanks for engaging!
