### ISSUE TITLE
Unable to run this app on localhost

### ISSUE THREAD

**Issue by YashAgrawal9265** [fossasia/open-event-legacy#84]
Hi,
My name is Yash Agrawal. I am newbie. I am interested in making contribution to this project.
I have also clone this repository and trying to run it in my pc. I had also follow all the steps for downloading this project, with the help of **docker**. but I am unable to run it on my localhost.

On running command **_docker-compose build && docker-compose up_**
I get the error which are show in the figure

<img width="960" alt="2020-10-22" src="https://user-images.githubusercontent.com/69956695/96776029-0f100700-1406-11eb-8e9d-4d324fbe343f.png">

Please can anyone help me ?

**Comment by mariobehling** [comment]
As the name says this is a legacy version. It is unmaintained. Newer versions of Open Event are here on Github as well. Closing this therefore.
